apiVersion: v1
appVersion: "1.0"
description: A Helm chart for myhero-app
name: myhero-app-helm
version: 1.0.0

mantainers:
  - name: Pedro Oliveira
  - email: peolivei@cisco.com
  - twitter:
  - GitHub: